models:
  ARIMA_TSLA: "models:/arima_model_TSLA/Production"
  SARIMA_TSLA: "models:/sarima_model_TSLA/Production"
  LSTM_TSLA: "models:/lstm_model_TSLA/Production"

  ARIMA_SPY: "models:/arima_model_SPY/Production"
  SARIMA_SPY: "models:/sarima_model_SPY/Production"
  LSTM_SPY: "models:/lstm_model_SPY/Production"

  SARIMA_BND: "models:/sarima_model_BND/Production"

forecast_horizon: 365
log_file: "./logs/forecast.log"
